Repository deis/docker-go-dev, pull requests merged in 2018-02, with the labels that each got.

#101 feat: add vim
  README.md
  rootfs/Dockerfile
Labels: LGTM2

#102 chore(rootfs/Dockerfile): update go toolchain to 1.9.4
  rootfs/Dockerfile
Labels: LGTM1, awaiting review, security

#103 chore(Dockerfile): update az CLI to 2.0.27
  rootfs/Dockerfile
Labels: LGTM1
