Repository deis/docker-go-dev, pull requests merged in 2018-12, with the labels that each got.

#141 Build helm client from source
  rootfs/Dockerfile
Labels: awaiting review, enhancement

#138 Migrate linting to use golangci-lint
  rootfs/Dockerfile
Labels: LGTM1

#142 chore(rootfs/Dockerfile): update go toolchain to 1.11.4
  rootfs/Dockerfile
Labels: awaiting review

#145 feat(/usr/local/bin/k): Install kubectl just-in-time
  README.md
  rootfs/usr/local/bin/k
Labels: awaiting review, enhancement
