Repository deis/docker-go-dev, pull requests merged in 2019-04, with the labels that each got.

#159 Add wamerican tool
  README.md
  rootfs/Dockerfile
Labels: LGTM1, awaiting review

#160 chore(rootfs/Dockerfile): update shellcheck to v0.6.0
  rootfs/Dockerfile
Labels: awaiting review

#161 chore(rootfs/Dockerfile): update golangci-lint to v1.16.0
  rootfs/Dockerfile
Labels: awaiting review

#162 chore(rootfs/Dockerfile): update helm to v2.13.1
  rootfs/Dockerfile
Labels: awaiting review

#163 feat(rootfs/Dockerfile): add azcopy v10 preview as `azcopy-preview`
  rootfs/Dockerfile
Labels: awaiting review, enhancement

#164 chore(rootfs/Dockerfile): update azure CLI to 2.0.61
  rootfs/Dockerfile
Labels: awaiting review

#165 chore(rootfs/Dockerfile): update go toolchain to 1.12.2
  rootfs/Dockerfile
Labels: awaiting review
